---
booktitle: Proceedings of the Third Learning on Graphs Conference
conference_number: '3'
end: 2024-11-29
published: 2025-07-30
sections:
- name: Oral Presentations
  title: Oral Presentations
- name: Poster Presentations
  title: Poster Presentations
shortname: LoG
start: &1 2024-11-26
volume: '269'
year: '2024'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: log24
month: 0
cycles: false
bibtex_editor: Wolf, Guy and Krishnaswamy, Smita
editor:
- given: Guy
  family: Wolf
- given: Smita
  family: Krishnaswamy
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Third Learning on Graphs Conference
    Held in Virtual on 26-29 November 2024

  Published as Volume 269 by the Proceedings of Machine Learning Research on 30 July 2025.

  Volume Edited by:
    Guy Wolf
    Smita Krishnaswamy

  Series Editors:
    Neil D. Lawrence
date_str: 26--29 Nov
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v269"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v269
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v269
email: ''
conference:
  name: Learning on Graphs Conference
  url: https://log2024.logconference.org/
  location: Virtual
  dates:
  - *1
  - 2024-11-27
  - 2024-11-28
  - 2024-11-29
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: log24_clean.bib
# Site settings
# Original source:  log24_clean.bib
